unset GEM_HOME GEM_PATH

VERSION=`rbenv version-name`

if [ "$VERSION" = "system" ]; then
  RBENV_GEMSET_ROOT="$RBENV_GEMSET_SYSTEM_ROOT"
else
  RBENV_GEMSET_ROOT="$HOME/.rbenv-usergems/$VERSION"
fi

GEM_HOME="$RBENV_GEMSET_ROOT"
GEM_PATH="$RBENV_GEMSET_ROOT:$GEM_PATH"

export GEM_HOME GEM_PATH
